version: "1"
services:
  backend:
    build: 
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app  
    command: bash -c "poetry install && poetry run python -m df_designer run-app --ip-address 0.0.0.0 --port 8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
      - REACT_APP_BACKEND_URL=http://backend:8000
      - REACT_APP_BACKEND_WS_URL=ws://backend:8000
    ports:
      - 5173:5173
    environment:
      - VITE_BASE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "cd ./frontend && bun install && bun run dev"